<?php
$game = $this->game;
?>
<div class="mid-content">
    <h4 title="<?php echo $game['game_desc'] ?>"><?php echo $game['game_name'] ?></h4>
    <p class="desc-booking-detail"><?php echo __('Please select your perferred time') ?></p>
    <div class="schedule-container week hidden-xs" id="week_booking">
        <?php require APPLICATION_PATH . '/modules/bookings/views/scripts/index/weektime.phtml'; ?>
    </div>
</div>
