<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Insert title here</title>
</head>
<body class="the-game">
<div style="background: #000">
    <header style="background: url('http://decode.com.vn/public/templates/default/default/_/component/images/Decode/top/bgtop.png') no-repeat; border-bottom: 5px solid red;">
        <div style="overflow: hidden; height: 150px; width: 1170px; margin: auto;">
            <h1 style="float: left; margin-top: 50px;"><img src="http://decode.com.vn/public/upload/83530_201410050847.ogo.png" alt = "logo" /></h1>
            <ul style="float: right; list-style: none; margin-top: 112px;">
                <li style="display: inline-block;"><a href="#" style="background: red;color: #fff; padding: 10px 15px; display: block; text-decoration: none; color: #fff; font-weight: bold;">Home</a></li>
                <li style="display: inline-block;"><a href="#" style="color: #fff; padding: 10px 15px; display: block; text-decoration: none; color: #fff; font-weight: bold;">The Game</a></li>
                <li style="display: inline-block;"><a href="#" style="color: #fff; padding: 10px 15px; display: block; text-decoration: none; color: #fff; font-weight: bold;">Booking</a></li>
                <li style="display: inline-block;"><a href="#" style="color: #fff; padding: 10px 15px; display: block; text-decoration: none; color: #fff; font-weight: bold;">Faq</a></li>
                <li style="display: inline-block;"><a href="#" style="color: #fff; padding: 10px 15px; display: block; text-decoration: none; color: #fff; font-weight: bold;">Contact</a></li>
            </ul>
        </div><!-- .header-top -->

    </header>
    <section style="background: url('http://decode.com.vn/public/templates/default/default/_/component/images/Decode/background/bg_fire.png') no-repeat;">
        <div style="min-height: 200px; padding: 30px 0px; width: 1170px; margin: auto;">
            <p style="color: #fff">This is the content</p>
        </div>
    </section>
    <footer style="background: url('http://decode.com.vn/public/templates/default/default/_/component/images/Decode/top/bgtop.png') no-repeat; height: 52px; border-top: 2px solid #fff;">
        <div style="width: 1170px; margin: auto;">
            <p style="color: #fff; text-align: right;">Copyright © 2014 Tue Vi Co.Ltd.  All rights reserved. </p>
        </div>
    </footer>
</div>
</body>
</html>