
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Insert title here</title>
</head>
<body class="the-game">
<style type="text/css">
    *{margin: 0px; padding: 0px;}
    .wrapper{background: #000;}
    .container {width: 1170px; margin: auto;}
    p {color: #fff;}
    header {background: url("http://decode.com.vn/public/templates/default/default/_/component/images/Decode/top/bgtop.png") no-repeat; border-bottom: 5px solid red;}
    header .container {overflow: hidden; height: 150px;}
    header .container h1.logo {float: left; margin-top: 50px;}
    header .container ul.nav {float: right; list-style: none; margin-top: 112px;}
    header .container ul.nav li {display: inline-block; }
    header .container ul.nav li a{padding: 10px 15px; display: block; text-decoration: none; color: #fff; font-weight: bold;}
    header .container ul.nav li a.active {background: red;}
    footer {background: url("http://decode.com.vn/public/templates/default/default/_/component/images/Decode/top/bgtop.png") no-repeat; height: 52px; border-top: 2px solid #fff;}
    footer p {line-height: 52px; text-align: right;}
    section.content {background: url('http://decode.com.vn/public/templates/default/default/_/component/images/Decode/background/bg_fire.png') no-repeat;}
    section.content .container {min-height: 200px; padding: 30px 0px;}
</style>
<div class="wrapper">
    <header>
        <div class="container">
            <h1 class="logo"><img src="http://decode.com.vn/public/upload/83530_201410050847.ogo.png" alt = "logo" /></h1>
            <ul class="nav">
                <li><a href="#" class="active">Home</a></li>
                <li><a href="#">The Game</a></li>
                <li><a href="#">Booking</a></li>
                <li><a href="#">Faq</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </div><!-- .header-top -->

    </header>
    <section class="content">
        <div class="container">
            <p>This is the content</p>
        </div>
    </section>
    <footer>
        <div class="container">
            <p class="main-footer">Copyright © 2014 Tue Vi Co.Ltd.  All rights reserved. </p>
        </div>
    </footer>
</div>
</body>
</html>