<div class="schedule-container day visible-xs">
    <div class="row mmb schedule-bar">
        <div class="col-xs-5">
            <a href="#" class="btn schedule-control prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
        </div>
        <div class="col-xs-2 text-center">
            <span class="schedule-week"></span>
        </div>
        <div class="col-xs-5 text-right">
            <a href="#" class="btn schedule-control next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr>
            <td><p>Sun</p>

                <p>(26/10/2014)</p></td>
        </tr>
        </thead>

        <tr>
            <td>10:45</td>
        </tr>
        <tr>
            <td>10:45</td>
        </tr>
        <tr>
            <td class="acti">10:45</td>
        </tr>
        <tr>
            <td>10:45</td>
        </tr>
        <tr>
            <td>10:45</td>
        </tr>
        <tr>
            <td class="reserved">Reserved</td>
        </tr>
        <tr>
            <td>10:45</td>
        </tr>

    </table>
</div><!-- schedule-container day visible-xs -->