<?php
$list_time = $this->list_time;
$arr_week_date = $this->week_date;
$languages = New Zend_Session_Namespace('languages');
$date_format = 'd/m/Y';
if ($languages->languages === 'en') {
    $date_format = 'm/d/Y';
}
$curent_time = strtotime('now');
$arr_date_key = array(
    __('Mon'),
    __('Tue'),
    __('Wed'),
    __('Thu'),
    __('Fri'),
    __('Sat'),
    __('Sun')
);
?>
<style>
    .booking-detail .mid-content table tbody tr td.acti a{
        color: #ada1a1 !important;
        cursor: auto;
    }
    td.acti a:hover,td.acti:hover{ color: #ada1a1 !important;cursor: auto;}
</style>
<div class="row mmb schedule-bar">
    <div class="col-xs-12 col-sm-3 col-md-2">
        <a href="#" class="btn schedule-control prev" data="<?php echo reset($arr_week_date) ?>" data-compare="<?php echo date($date_format, strtotime(reset($arr_week_date))) ?>">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-8 text-center">
        <span class="schedule-week"><?php echo date($date_format, strtotime(reset($arr_week_date))) . ' - ' . date($date_format, strtotime(end($arr_week_date))) ?></span>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-2 text-right">
        <a href="#" class="btn schedule-control next" data="<?php echo end($arr_week_date) ?>" data-compare="<?php echo date($date_format, strtotime(end($arr_week_date))) ?>">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>
</div>
<table class="table table-responsive">
    <thead>
        <tr>
            <?php foreach ($arr_week_date as $key => $date_value): ?>
                <?php $date_value = date($date_format, strtotime($date_value)); ?>
                <td><p><?php echo $key ?></p><p class="">(<?php echo $date_value; ?>)</p></td>
            <?php endforeach; ?>
        </tr>
        <tr class="space"></tr>
    </thead>
    <tbody>
        <?php foreach ($list_time as $time): ?>
            <?php
            $time_value = date('H:i', strtotime($time['time_value']));
            ?>
            <tr align="center">
                <?php for ($i = 0; $i < 7; $i++): ?>
                <?php 
                    $class_td = '';
                    $href = '';
                    if(strtotime($arr_week_date[$arr_date_key[$i]].' '.$time_value) < $curent_time){
                        $class_td = 'acti';
                    }else{
                        $href = "href='#'";
                    }
                ?>
                    <td class="<?php echo $class_td?>">
                        <a <?php echo $href;?>><?php echo $time_value ?></a>
                    </td>
                <?php endfor; ?>
            </tr>
            <tr class="space"></tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script>
    $(document).ready(function() {
        $('.prev').click(function() {
            var date = $(this).attr('data');
            load_week_booking(date, 'prev');
        });
        $('.next').click(function() {
            var date = $(this).attr('data');
            load_week_booking(date, 'next');
        });
        dsp_prev_next(get_current_date(), get_end_date_week());
    });
    function dsp_prev_next(date_cur, date_week) {
        if (date_cur === $('.prev').attr('data-compare')) {
            $('.prev').hide();
        } else {
            $('.prev').show();
        }
        if (date_week === $('.next').attr('data-compare')) {
            $('.next').hide();
        } else {
            $('.next').show();
        }
    }

    function get_current_date() {
        var datetime = new Date();
        var current_date = (datetime.getDate() - 1) + "/"
                + (datetime.getMonth() + 1) + "/"
                + datetime.getFullYear();
        return current_date;
    }
    function get_end_date_week() {
        var datetime = new Date();
        var date_time = new Date($.now() + (3 * 7 * 24 * 60 * 60 * 1000) - (datetime.getDay() * 24 * 60 * 60 * 1000));
        var week_end_date = (date_time.getDate()) + "/"
                + (date_time.getMonth() + 1) + "/"
                + date_time.getFullYear();
        return week_end_date;
    }
    function load_week_booking(date_data, action)
    {
        $.ajax({
            type: 'POST',
            url: '<?php echo HTTP_BASE . $this->baseUrl('bookings/index/weektime/') ?>',
            data: {date: date_data, action_event: action},
            beforeSend: function(xhr) {
                var html = '<img width="100%" height="100%" src="<?php echo TEMPLATE_URL . '/default/default/img/loading.gif' ?>"/>';
                $('#week_booking').html(html);
            },
            success: function(data, textStatus, jqXHR) {
                $('#week_booking').html(data);
            },
            error: function(jqXHR, textStatus, errorThrown) {
                $('#week_booking').html('<h2><?php echo __('error data') ?></h2>');
            }
        });
    }
</script>
