<?php
$game = $this->game;
$deviation_time = $game['deviation_time'];
$list_time = $this->list_time;
$arr_week_date = $this->week_date;
$list_bookings = $this->list_bookings;
$languages = New Zend_Session_Namespace('languages');
$date_format = 'd/m/Y';
if ($languages->languages === 'en') {
    $date_format = 'm/d/Y';
}
$curent_time = strtotime('now');
$arr_date_key = array(
    __('Mon'),
    __('Tue'),
    __('Wed'),
    __('Thu'),
    __('Fri'),
    __('Sat'),
    __('Sun') 
);
?>
<style>
    .booking-detail .mid-content table tbody tr td.acti a{
        color: #ada1a1 !important;
        cursor: default;
    }
    td.acti a:hover,td.acti:hover{ color: #ada1a1 !important;cursor: default;}
</style>
<div class="row mmb schedule-bar">
    <div class="col-xs-12 col-sm-3 col-md-2">
        <?php 
        $date_com = strtotime(reset($arr_week_date)) ;
        if(strtotime(reset($arr_week_date)) < strtotime('now')){
            $date_com = strtotime('now');
        }
        ?>
        <a href="#" class="btn schedule-control prev" data="<?php echo reset($arr_week_date) ?>" data-compare="<?php echo date($date_format, $date_com) ?>">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-8 text-center">
        <span class="schedule-week"><?php echo date($date_format, strtotime(reset($arr_week_date))) . ' - ' . date('d/m/Y', strtotime(end($arr_week_date))) ?></span>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-2 text-right">
        <a href="#" class="btn schedule-control next" data="<?php echo end($arr_week_date) ?>" data-compare="<?php echo date('d/m/Y', strtotime(end($arr_week_date))) ?>">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>
</div>
<div class="table-responsive">
<table class="table">
    <thead>
        <tr>
            <?php foreach ($arr_week_date as $key => $date_value): ?>
                <?php $date_value = date($date_format, strtotime($date_value)); ?>
                <td><p><?php echo $key ?></p><p class="">(<?php echo $date_value; ?>)</p></td>
            <?php endforeach; ?>
        </tr>
        <tr class="space"></tr>
    </thead>
    <tbody>
        <?php foreach ($list_time as $time): ?>
            <?php
                if($deviation_time == 0){
                    $time_value = date('H:i', strtotime($time['time_value']));
                }else{
                    $time_value = date('H:i', strtotime($time['time_value']."$deviation_time minutes"));
                }
            ?>
            <tr align="center">
                <?php for ($i = 0; $i < 7; $i++): ?>
                    <?php
                    $class_td = '';
                    $class_a = '';
                    $__date = $arr_week_date[$arr_date_key[$i]];
                    if (strtotime($__date . ' ' . $time_value) < $curent_time) {
                        $class_td = 'acti';
                    }else{
                        $class_a='booking_info';
                    }
                    $exist_booking = FALSE;
                    foreach ($list_bookings as $booking) {
                        if (strtotime($booking['time']) === strtotime($time_value) && strtotime($booking['date']) == strtotime($__date)) {
                            $exist_booking = TRUE;
                            break;
                        }
                    }
                    $weekend = 0;
                    if($i > 3){
                        $weekend = 1;
                    }
                    ?>
                    <?php if ($exist_booking && $class_a !== ''): ?>
                        <td class="reserved"><?php echo __('Reserved')?></td>
                    <?php else: ?>
                        <td class="<?php echo $class_td ?>">
                            <a class="<?php echo $class_a ?>" data_date="<?php echo $__date?>" data_time="<?php echo $time_value?>" weekend="<?php echo $weekend ?>"><?php echo $time_value ?></a>
                        </td>
                    <?php endif; ?>
                <?php endfor; ?>
            </tr>
            <tr class="space"></tr>
        <?php endforeach; ?>
    </tbody>
</table>
</div>
<script>
    $(document).ready(function() {
        $('.prev').click(function() {
            var date = $(this).attr('data');
            var game_id = $('#game').attr('data_id');
            load_week_booking(date, 'prev',game_id);
        });
        $('.next').click(function() {
            var game_id = $('#game').attr('data_id');
            var date = $(this).attr('data');
            load_week_booking(date, 'next',game_id);
        });
//        alert(get_current_date());
        dsp_prev_next(get_current_date(), get_end_date_week());
        
        //boking info
        $('.<?php echo $class_a?>').click(function (){
            var data_date = $(this).attr('data_date');
            var data_time = $(this).attr('data_time');
            var game_id = $('#game').attr('data_id');
            var weekend = $(this).attr('weekend');
            load_info_booking(data_date,data_time,game_id,weekend);
        });
    });
    function dsp_prev_next(date_cur, date_week) {
        if (date_cur === $('.prev').attr('data-compare')) {
            $('.prev').hide();
        } else {
            $('.prev').show();
        }
        if (date_week === $('.next').attr('data-compare')) {
            $('.next').hide();
        } else {
            $('.next').show();
        }
    }

    function get_current_date() {
        var datetime = new Date();
        var date_now = datetime.getDate();
        if(date_now < 10){
            date_now = '0'+date_now;
        }
        var current_date = (date_now) + "/"
                + (datetime.getMonth() + 1) + "/"
                + datetime.getFullYear();
        return current_date;
    }
    function get_end_date_week() {
        var datetime = new Date();
        var date_time = new Date($.now() + (3 * 7 * 24 * 60 * 60 * 1000) - (datetime.getDay() * 24 * 60 * 60 * 1000));
        var week_end_date = (date_time.getDate()) + "/"
                + (date_time.getMonth() + 1) + "/"
                + date_time.getFullYear();
        return week_end_date;
    }
    function load_info_booking(date_data, data_time,game_id,weekend)
    {
        var html_before = $('#week_booking').html();
        $.ajax({
            type: 'POST',
            url: '<?php echo HTTP_BASE . $this->baseUrl('bookings/index/infoboking/') ?>',
            data: {date_data: date_data, time_data: data_time, game_id:game_id,weekend:weekend},
            beforeSend: function(xhr) {
                $('.desc-booking-detail').text('<?php echo __('Please fill in your details') ?>');
                var html = '<img width="100%" height="100%" src="<?php echo TEMPLATE_URL . '/default/default/img/loading.gif' ?>"/>';
                $('#week_booking').html(html);
            },
            success: function(data, textStatus, jqXHR) {
                $('.desc-booking-detail').text('<?php echo __('Please fill in your details') ?>');
                if(data !== 'false'){
                    $('#week_booking').html(data);
                }else{
                    alert('<?php echo __('error data')?>');
                    $('#week_booking').html(html_before);
                }
            },
            error: function(jqXHR, textStatus, errorThrown) {
                $('.desc-booking-detail').text('<?php echo __('Please fill in your details') ?>');
                $('#week_booking').html('<h2><?php echo __('error data') ?></h2>');
            }
        });
    }
    function load_week_booking(date_data, action, game_id)
    {
        var html_before = $('#week_booking').html();
        $.ajax({
            type: 'POST',
            url: '<?php echo HTTP_BASE . $this->baseUrl('bookings/index/weektime/')?>',
            data: {date: date_data, action_event: action, game_id:game_id},
            beforeSend: function(xhr) {
                $('.desc-booking-detail').text('<?php echo __('Please select your perferred time') ?>');
                var html = '<img width="100%" height="100%" src="<?php echo TEMPLATE_URL . '/default/default/img/loading.gif' ?>"/>';
                $('#week_booking').html(html);
            },
            success: function(data, textStatus, jqXHR) {
                $('.desc-booking-detail').text('<?php echo __('Please select your perferred time') ?>');
                if(data !== 'false'){
                    $('#week_booking').html(data);
                }else{
                    alert('<?php echo __('error data')?>');
                    $('#week_booking').html(html_before);
                }
            },
            error: function(jqXHR, textStatus, errorThrown) {
                $('.desc-booking-detail').text('<?php echo __('Please select your perferred time') ?>');
                $('#week_booking').html('<h2><?php echo __('error data') ?></h2>');
            }
        });
    }
</script>
