<?php
$linkStart = $this->currentUrl . '/page/' . $this->first;

$linkPrevious = 'javascript:void(0)';
if (isset($this->previous))
{
    $linkPrevious = $this->currentUrl . '/page/' . $this->previous;
}
$linkNext = 'javascript:void(0)';
if (isset($this->next))
{
    $linkNext = $this->currentUrl . '/page/' . $this->next;
}

$linkEnd = $this->currentUrl . '/page/' . $this->last;

$strPage = '';
foreach ($this->pagesInRange as $key)
{
    if ($this->current == $key)
    {
        $strPage .= '<li><a href="javascript:void(0)" class="current_page" title="'.__('page').' '.$key.'">' . $key . '</a></li>';
    }
    else
    {
        $linkPage = $this->currentUrl . '/page/' . $key;
        $strPage .= '<li><a href="' . $linkPage . '" title="'.__('page').' '.$key.'">' . $key . '</a></li>';
    }
}

$page = __('page') . ' ' . $this->current . ' ' . __('of') . ' ' . $this->last;
?>
<div class="div-pagination">
    <ul class="pagination">
        <li><a href="<?php echo $linkStart; ?>" title="<?php echo __('start')?>"><?php echo __('start') ?></a></li>
        <li><a href="<?php echo $linkPrevious; ?>" title="<?php echo __('prev')?>"><?php echo __('&lt') ?></a></li>
        <?php echo $strPage ?>
        <li><a href="<?php echo $linkNext; ?>" title="<?php echo __('next')?>"><?php echo __('&gt'); ?></a></li>
        <li><a href="<?php echo $linkEnd; ?>" title="<?php echo __('end')?>"><?php echo __('end') ?></a></li>
<!--        <li>--><?php //echo $page ?><!--</li>-->
    </ul>    
</div>
