<?php
$pricesCollection = $this->pricesCollection;
$countRecord = count($pricesCollection);
$no= 1;
?>
<!-- Page heading -->
<div class="page-head">
    <!-- Page heading -->
    <h2 class="pull-left"><?php echo __('price') ?>
        <!-- page meta -->
        <span class="page-meta"><?php echo __('list price') ?></span>
    </h2>
    <!-- Breadcrumb -->
    <div class="bread-crumb pull-right">
        <a href="<?php echo $this->baseUrl('admin') ?>"><i class="fa fa-home"></i><?php echo __('Home') ?></a>
        <!-- Divider -->
        <span class="divider">/</span> 
        <a href="javascript:void(0)" class="bread-current"><?php echo __('price') ?></a>
    </div>
    <div class="clearfix"></div>
    <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
    <?php if ($flashMessenger->setNamespace('success')->hasMessages()): ?>
        <div class="alert alert-success">
            <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                <?php echo __($msg) ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <?php if ($flashMessenger->setNamespace('fail')->hasMessages()): ?>
        <div class="alert alert-warning">
            <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                <?php echo $msg ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div> <!--/ Page heading ends -->
<div class="matter">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="widget wred">
                    <div class="widget-head">
                        <div class="pull-left"><?php echo __('list price') ?></div>
                        <div class="widget-icons pull-right">
                            <a href="<?php echo $this->baseUrl('admin/prices/update'); ?>" class=""><?php echo __('add new price')?></a>
                            <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="widget-content">
                        <table class="table table-bordered ">
                            <thead>
                            <tr>
                                <th><?php echo __('STT')?></th>
                                <th><?php echo __('prices type')?></th>
                                <th><?php echo __('code')?></th>
                                <th><?php echo __('prices')?></th>
                                <th><?php echo __('status')?></th>
                                <th><?php echo __('action')?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if(count($pricesCollection) > 0):?>
                                <?php foreach($pricesCollection as $price):?>
                                    <?php
                                    if($price['price_status'] == 1){
                                        $class = 'label-success';
                                        $priceStatus = __('active');
                                        $href = $this->baseUrl('admin/prices/updatestatus/id/'.$price['price_id'].'/status/0');
                                    }else{
                                        $class = 'label-important';
                                        $priceStatus = __('not active');
                                        $href = $this->baseUrl('admin/prices/updatestatus/id/'.$price['price_id'].'/status/1');
                                    }
                                    ?>
                                <?php $price_code = unserialize(PRICE_CODE); ?>
                                    <tr>
                                        <td><?php echo $no ?></td>
                                        <td><?php echo $price['price_name'] ?></td>
                                        <td><?php echo __($price_code[$price['price_code']]) ?></td>
                                        <td><?php echo $price['price_value'] ?> VNĐ</td>
                                        <td><a href="<?php echo $href ?>"><span class="label <?php echo $class?>"><?php echo $priceStatus ?></span></a></td>
                                        <td>
                                            <div class="btn-group">
                                                <a href="<?php echo $this->baseUrl('admin/prices/update/id/'.$price['price_id']); ?>" class="btn btn-sm btn-warning">
                                                    <i class="fa fa-pencil"></i>
                                                </a>
                                            </div>
                                            <a class="btn btn-sm btn-danger" href="<?php echo $this->baseUrl('admin/prices/delete/id/'.$price['price_id']); ?>" onclick="return confirm('<?php echo __('are you sure?') ?>')"><i class="fa fa-times"></i></a>
                                        </td>
                                    </tr>
                                    <?php $no++ ?>
                                <?php endforeach; ?>
                            <?php else:?>
                                    <tr>
                                        <td colspan="6"><?php echo __('no data')?></td>
                                    </tr>
                            <?php endif;?>
                            </tbody>
                        </table>
                    </div>
                    <div class="widget-foot">
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!--/ Matter ends -->
