<!--TrangVT-->
<?php
$singlePrice = $this->singlePrice;
$price_id = $singlePrice['price_id'];
?>
<!-- Page heading -->
<div class="page-head">
    <!-- Page heading -->
    <h2 class="pull-left"><?php echo __('price') ?>
        <!-- page meta -->
        <span class="page-meta"><?php echo __('list price') ?></span>
    </h2>
    <!-- Breadcrumb -->
    <div class="bread-crumb pull-right">
        <a href="<?php echo $this->baseUrl('admin') ?>"><i class="fa fa-home"></i><?php echo __('Home') ?></a>
        <!-- Divider -->
        <span class="divider">/</span> 
        <a href="javascript:void(0)" class="bread-current"><?php echo __('price') ?></a>
    </div>
    <div class="clearfix"></div>
    <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
    <?php if ($flashMessenger->setNamespace('success')->hasMessages()): ?>
        <div class="alert alert-success">
            <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                <?php echo __($msg) ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <?php if ($flashMessenger->setNamespace('fail')->hasMessages()): ?>
        <div class="alert alert-warning">
            <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                <?php echo $msg ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <?php if (isset($this->messages)): ?>
        <div class="alert alert-warning">
            <?php if (is_array($this->messages)): ?>
                <?php foreach ($this->messages as $filed => $arr_mess): ?>
                    <?php foreach ($arr_mess as $mess): ?>
                        <span style="display: block;"> <?php echo __($mess) ?> </span>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            <?php else: ?>
                <?php echo $this->messages ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div> <!--/ Page heading ends -->
<div class="matter">
    <div class="col-md-12">
        <div class="widget wred">
            <div class="widget-head">
                <div class="pull-left"><?php if($price_id){echo __('edit price');}else{echo __('add new price');}?></div>
                <div class="widget-icons pull-right">
                    <a href="<?php echo $this->baseUrl('admin/prices/index/'); ?>"><?php echo __('back')?></a>
                    <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="widget-content">
                <div class="padd">
                    <div class="form quick-post">
                        <form class="form-horizontal" role="form" action="<?php echo $this->baseUrl('admin/prices/update/id/'.$price_id); ?>" method="post">
                            <input type="hidden" name="price_id" value="<?php echo $singlePrice['price_id'] ?>"/>
                            <input type="hidden" name="price_lang" value="<?php echo $singlePrice['price_lang'] ?>"/>
                            <!-- Price Type -->
                            <div class="form-group">
                                <label class="control-label col-md-2" for="sitename"><?php echo __('prices type')?></label>
                                <div class="col-md-7">
                                    <input type="text" class="form-control" id="sitename" name="price_name" value="<?php echo $singlePrice['price_name'] ?>">
                                </div>
                            </div>
                            <!-- Price Desc -->
                            <div class="form-group">
                                <label class="control-label col-lg-2" for="sitedescription"><?php echo __('prices desc')?></label>
                                <div class="col-lg-7">
                                    <textarea class="form-control ckeditor" name="price_desc" id="sitedescription"><?php echo $singlePrice['price_desc'] ?></textarea>
                                </div>
                            </div>
                            <!-- Price -->
                            <div class="form-group">
                                <label class="control-label col-md-2" for="sitename"><?php echo __('prices')?></label>
                                <div class="col-md-3">
                                    <input type="text" class="form-control" id="sitename" name="price_value" value="<?php echo $singlePrice['price_value'] ?>">
                                </div>
                                <div class="col-md-4">VNĐ</div>
                            </div>
                            <!--price code-->
                            <div class="form-group">
                                <label class="control-label col-lg-2"><?php echo __('code')?></label>
                                <div class="col-md-3">
                                    <select name="price_code" class="form-control">
                                        <?php foreach (unserialize(PRICE_CODE) as $key => $code):?>
                                        <option value="<?php echo $key?>" <?php echo $singlePrice['price_code']=== $key?'selected':''?>>
                                            <?php echo __($code)?>
                                        </option>
                                        <?php endforeach;?>
                                    </select>
                                </div>
                            </div>
                            <!-- Price Status -->
                            <div class="form-group">
                                <label class="control-label col-lg-2"><?php echo __('status')?></label>
                                <div class="col-lg-7">
                                    <div class="radio">
                                        <label><input type="radio" name="<?php echo "price_status" ?>" id="1" value="1" <?php if($singlePrice['price_status'] == 1){echo 'checked';}?>><?php echo __('active')?></label>
                                    </div>
                                    <div class="radio">
                                        <label><input type="radio" name="<?php echo "price_status" ?>" id="0" value="0" <?php if($singlePrice['price_status'] == 0){echo 'checked';}?>><?php echo __('not active')?></label>
                                    </div>
                                </div>
                            </div>
                            <!-- Buttons -->
                            <div class="form-group">
                                <!-- Buttons -->
                                <div class="col-lg-9 col-lg-offset-2">
                                    <button type="submit" class="btn btn-primary"><?php echo __('Save Now') ?></button>
                                    <button type="reset" class="btn btn-default"><?php echo __('Reset') ?></button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>