<?php
$timesCollection = $this->timesCollection;
$countRecord = count($timesCollection);
$no= 1;
?>
<!-- Page heading -->
<div class="page-head">
    <!-- Page heading -->
    <h2 class="pull-left"><?php echo __('price') ?>
        <!-- page meta -->
        <span class="page-meta"><?php echo __('list price') ?></span>
    </h2>
    <!-- Breadcrumb -->
    <div class="bread-crumb pull-right">
        <a href="<?php echo $this->baseUrl('admin') ?>"><i class="fa fa-home"></i><?php echo __('Home') ?></a>
        <!-- Divider -->
        <span class="divider">/</span> 
        <a href="javascript:void(0)" class="bread-current"><?php echo __('price') ?></a>
    </div>
    <div class="clearfix"></div>
    <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
    <?php if ($flashMessenger->setNamespace('success')->hasMessages()): ?>
        <div class="alert alert-success">
            <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                <?php echo __($msg) ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <?php if ($flashMessenger->setNamespace('fail')->hasMessages()): ?>
        <div class="alert alert-warning">
            <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                <?php echo $msg ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <?php if (isset($this->messages)): ?>
        <div class="alert alert-warning">
            <?php if (is_array($this->messages)): ?>
                <?php foreach ($this->messages as $filed => $arr_mess): ?>
                    <?php foreach ($arr_mess as $mess): ?>
                        <span style="display: block;"> <?php echo __($mess) ?> </span>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            <?php else: ?>
                <?php echo $this->messages ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div> <!--/ Page heading ends -->
<div class="matter">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="widget wred">
                    <div class="widget-head">
                        <div class="pull-left"><?php echo __('list time') ?></div>
                        <div class="widget-icons pull-right">
                            <a href="<?php echo $this->baseUrl('admin/times/update'); ?>" class=""><?php echo __('add new time')?></a>
                            <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="widget-content">
                        <table class="table table-bordered ">
                            <thead>
                            <tr>
                                <th><?php echo __('STT')?></th>
                                <th><?php echo __('times')?></th>
                                <th><?php echo __('status')?></th>
                                <th><?php echo __('action')?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if(count($timesCollection) > 0 ):?>
                                <?php foreach($timesCollection as $times):?>
                                    <?php
                                    if($times['time_status'] == 1){
                                        $class = 'label-success';
                                        $timeStatus = __('active');
                                        $href = $this->baseUrl('admin/times/updatestatus/id/'.$times['time_id'].'/status/0');
                                    }else{
                                        $class = 'label-important';
                                        $timeStatus = __('not active');
                                        $href = $this->baseUrl('admin/times/updatestatus/id/'.$times['time_id'].'/status/1');
                                    }
                                    ?>
                                    <?php
                                    $time_value = date('H:i',strtotime($times['time_value']));
                                    ?>
                                    <tr>
                                        <td><?php echo $no ?></td>
                                        <td><?php echo  $time_value ?></td>
                                        <td><a href="<?php echo $href ?>"><span class="label <?php echo $class?>"><?php echo $timeStatus ?></span></a></td>
                                        <td>
                                            <div class="btn-group">
                                                <a href="<?php echo $this->baseUrl('admin/times/update/id/'.$times['time_id']); ?>" class="btn btn-sm btn-warning">
                                                    <i class="fa fa-pencil"></i>
                                                </a>
                                            </div>
                                            <a class="btn btn-sm btn-danger" onclick="return confirm('<?php echo __('are you sure?')?>');" href="<?php echo $this->baseUrl('admin/times/delete/id/'.$times['time_id']); ?>"><i class="fa fa-times"></i></a>
                                        </td>
                                    </tr>
                                    <?php $no++ ?>
                                <?php endforeach; ?>
                             <?php else:?>
                                    <tr>
                                        <td colspan="6"><?php echo __('no data')?></td>
                                    </tr>
                             <?php endif;?>
                            </tbody>
                        </table>
                    </div>
                    <div class="widget-foot">
                        <?php
                        if(count($timesCollection) > 0){
                            $currentUrl = $this->baseUrl($this->currentController.'/index');
                            echo $this->paginationControl($this->pagination, 'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl));
                        }
                        ?>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!--/ Matter ends -->