<?php
$singleTime = $this->singleTime;
$time_id = $singleTime['time_id'];
?>
<!-- Page heading -->
<div class="page-head">
    <!-- Page heading -->
    <h2 class="pull-left"><?php echo __('price') ?>
        <!-- page meta -->
        <span class="page-meta"><?php echo __('list price') ?></span>
    </h2>
    <!-- Breadcrumb -->
    <div class="bread-crumb pull-right">
        <a href="<?php echo $this->baseUrl('admin') ?>"><i class="fa fa-home"></i><?php echo __('Home') ?></a>
        <!-- Divider -->
        <span class="divider">/</span> 
        <a href="javascript:void(0)" class="bread-current"><?php echo __('price') ?></a>
    </div>
    <div class="clearfix"></div>
    <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
    <?php if ($flashMessenger->setNamespace('success')->hasMessages()): ?>
        <div class="alert alert-success">
            <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                <?php echo __($msg) ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <?php if ($flashMessenger->setNamespace('fail')->hasMessages()): ?>
        <div class="alert alert-warning">
            <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                <?php echo $msg ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
     <?php if (isset($this->messages)): ?>
        <div class="alert alert-warning">
            <?php if (is_array($this->messages)): ?>
                <?php foreach ($this->messages as $filed => $arr_mess): ?>
                    <?php foreach ($arr_mess as $mess): ?>
                        <span style="display: block;"> <?php echo __($mess) ?> </span>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            <?php else: ?>
                <?php echo $this->messages ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div> <!--/ Page heading ends -->
<div class="col-md-12">
    <div class="widget wred">
        <div class="widget-head">
            <div class="pull-left"><?php if($time_id){echo __('edit time');}else{echo __('add new time');}?></div>
            <div class="widget-icons pull-right">
                <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                <a href="<?php echo $this->baseUrl('admin/times/'); ?>"><?php echo __('back')?></a>
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="widget-content">
            <div class="padd">

                <div class="form quick-post">
                    <form class="form-horizontal" role="form" action="<?php echo $this->baseUrl('admin/times/update/id/'.$time_id); ?>" method="post">
                        <input type="hidden" name="time_id" value="<?php echo $singleTime['time_id'] ?>"/>
                        <!--Time-->
                        <div class="form-group">
                            <label class="control-label col-lg-2"><?php echo __('times') ?></label>
                            <div class="col-lg-7">
                                <div id="datetimepicker2" class="input-append">
                                    <?php
                                    $time_value = date('H:i',strtotime($singleTime['time_value']));
                                    ?>
                                    <input readonly="true" data-format="hh:mm" class="picker" type="text" value="<?php echo $time_value ?>" name="time">
                                    <span class="add-on">
                                      &nbsp;<i data-time-icon="fa fa-clock-o"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <!-- Time Status -->
                        <div class="form-group">
                            <label class="control-label col-lg-2"><?php echo __('status')?></label>
                            <div class="col-lg-7">
                                <div class="radio">
                                    <label><input type="radio" name="<?php echo "time_status" ?>" id="1" value="1" <?php if($singleTime['time_status'] == 1){echo 'checked';}?>><?php echo __('active')?></label>
                                </div>
                                <div class="radio">
                                    <label><input type="radio" name="<?php echo "time_status" ?>" id="0" value="0" <?php if($singleTime['time_status'] == 0){echo 'checked';}?>><?php echo __('not active')?></label>
                                </div>
                            </div>
                        </div>
                        <!-- Buttons -->
                        <div class="form-group">
                            <!-- Buttons -->
                            <div class="col-lg-9 col-lg-offset-2">
                                <button type="submit" class="btn btn-primary"><?php echo __('Save Now') ?></button>
                                <button type="reset" class="btn btn-default"><?php echo __('Reset') ?></button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>


</div>